import { CheckCircle2, Code2, MapPin } from 'lucide-react';
import { ScrollReveal } from '../ScrollReveal/ScrollReveal.jsx';
import './About.css';

const highlights = ['Responsive', 'Clean', 'Fast', 'Maintainable'];

export function About() {
  return <section id="about" className="section-shell section-block about-section editorial-section"><div className="section-kicker"><span>01</span><p>About me</p></div><div className="about-editorial"><ScrollReveal><div><p className="eyebrow">A little context</p><h2>I like turning a blank canvas into a website that <em>actually works.</em></h2></div></ScrollReveal><ScrollReveal animation="fade-left" delay={120}><div className="about-copy"><p>I'm Manas, a WordPress Developer from Nallasopara, Mumbai. I build websites that are clean, responsive, easy to manage, and shaped around what a business really needs.</p><p>I work across WordPress, Elementor, PHP, and JavaScript with a close eye on usability, performance, and the details that make a site feel considered.</p><div className="about-place"><MapPin size={17} /><span>Nallasopara, Mumbai, Maharashtra, India</span></div></div></ScrollReveal></div><div className="about-details"><div className="about-detail"><span>Based in</span><strong>Nallasopara, Mumbai</strong></div><div className="about-detail"><span>Focus</span><strong>WordPress Development</strong></div><div className="about-detail"><span>Building with</span><strong>WordPress / Elementor / PHP / JS</strong></div><div className="about-detail"><span>Available for</span><strong>Freelance & opportunities</strong></div></div><div className="highlight-grid">{highlights.map((item, index) => <ScrollReveal key={item} delay={index * 70}><div className="highlight"><span>0{index + 1}</span><CheckCircle2 size={16} /><strong>{item}</strong></div></ScrollReveal>)}</div></section>;
}
