import { useState } from 'react';
import { ArrowUpRight, Mail, MapPin, Phone } from 'lucide-react';
import { ScrollReveal } from '../ScrollReveal/ScrollReveal.jsx';

export function Contact() {
  const [form, setForm] = useState({ name: '', email: '', subject: '', message: '' });
  const [error, setError] = useState('');
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = (event) => { event.preventDefault(); if (Object.values(form).some((value) => !value.trim())) { setError('Please complete all fields before sending.'); return; } if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) { setError('Please enter a valid email address.'); return; } setError(''); const body = `Name: ${form.name}\nEmail: ${form.email}\n\n${form.message}`; window.location.href = `mailto:manavvyas0205@gmail.com?subject=${encodeURIComponent(form.subject)}&body=${encodeURIComponent(body)}`; };
  return <section id="contact" className="contact-section"><div className="section-shell section-block"><div className="section-kicker"><span>06</span><p>Get in touch</p></div><div className="contact-heading"><ScrollReveal><h2>Let's build something <em>together.</em></h2><p>Have a project in mind or need help with your WordPress website? Feel free to get in touch.</p></ScrollReveal></div><div className="contact-grid"><ScrollReveal><div className="contact-info"><a href="mailto:manavvyas0205@gmail.com"><Mail size={17} /> manavvyas0205@gmail.com</a><a href="tel:9484646252"><Phone size={17} /> 9484646252</a><span><MapPin size={17} /> Nallasopara, Mumbai, Maharashtra, India</span><div className="availability-note"><i /> Currently open to new projects</div></div></ScrollReveal><ScrollReveal animation="fade-left" delay={140}><form className="contact-form" onSubmit={submit} noValidate><div className="form-row"><label>Name<input name="name" value={form.name} onChange={update} placeholder="Your name" /></label><label>Email<input type="email" name="email" value={form.email} onChange={update} placeholder="you@example.com" /></label></div><label>Subject<input name="subject" value={form.subject} onChange={update} placeholder="What can I help with?" /></label><label>Message<textarea name="message" value={form.message} onChange={update} placeholder="Tell me a little about your project..." rows="5" /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-primary" type="submit">Send Message <ArrowUpRight size={17} /></button><small>This opens your email app with the message ready to send.</small></form></ScrollReveal></div></div></section>;
}
